### ISSUE TITLE
|> orPanic Errors on lines 88, 89, and 95

### ISSUE THREAD

**Issue by Nadelio** [Nadelio/SimpleStack#3]
![image](https://github.com/user-attachments/assets/5c1f7bed-ae58-49b7-9942-c540475a9a72)
![image](https://github.com/user-attachments/assets/b5bb02f7-a3cc-406e-b239-9b9405cd30d4)

**Comment by gavr123456789** [comment]
Idk were this some recent changes or not, but cant reproduce it now 
<img width="908" alt="image" src="https://github.com/user-attachments/assets/2110b8d7-0a0d-4629-847c-933e649690dd">
